//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentGradeInformation.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Lesson()
        {
            this.tbl_Notes = new HashSet<tbl_Notes>();
        }
    
        public int lessonId { get; set; }
        public string lessonName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Notes> tbl_Notes { get; set; }
    }
}
